### ISSUE TITLE
See pictures of the icons

### ISSUE THREAD

**Issue by matejthetree** [brianegan/font_awesome_flutter#14]
It is really handy to have pictures next to icons like flutter Icons. Any chance this might be implemented here, or idea how to do it so I can do it?

**Comment by brianegan** [comment]
Hey hey :) Quick follow-up Q: "It is really handy to have pictures next to icons like flutter Icons." -- Do you mean a website that shows the icons? Or how they function in IntelliJ, where you can see the Icon?

**Comment by matejthetree** [comment]
Flutter intellij. Other icon pack that you made has thr pictures as well :)

**Comment by brianegan** [comment]
The open iconic package I've published? Hrm, I hadn't seen those working in IntelliJ! I assumed they wouldn't work because I figured the plugin is doing something special for the Material Icons pack, such as including that font asset with the plugin itself.

Overall, I think it's a really cool idea, and I had considered filing a bug on the Flutter IntelliJ project to support custom icon packs in general.

Could you please post a screenshot of what's working? At least for me, none of my custom icon packs show up in IntelliJ.

**Comment by matejthetree** [comment]
Indeed, I was positive that I saw icon images on OpenIconic pack, but now I see none. I will follow the issue for future request. Thank you

**Comment by brianegan** [comment]
Sounds good! I don't think I can do anything from inside this package just yet, so I'll go ahead and close it out since I think only the IntelliJ Flutter plugin can handle this request.
