### ISSUE TITLE
Icons do not work after the latest change

### ISSUE THREAD

**Issue by kostaa** [brianegan/font_awesome_flutter#2]
Here is a snapshot from your example app:

![image](https://user-images.githubusercontent.com/7585117/33736072-3822aa5c-db89-11e7-909c-c792515a81a4.png)

**Comment by brianegan** [comment]
Oh dang, not sure why I didn't get a notification for this! Is this still a problem on your end? The example works fine for me using the 5.0.0 package...

**Comment by kostaa** [comment]
Hi I just checked out your projects and run your example as it is and getting the above on the simulator and my mobile as well. Here is the 'doctor' output maybe that can help?

Regards,
Adam

[√] Flutter (on Microsoft Windows [Version 10.0.16299.125], locale en-GB, channel master)
    • Flutter at C:\DevTools\Flutter
    • Framework revision 4d2c2aaaa1 (5 days ago), 2017-12-27 07:30:31 -0800
    • Engine revision 7c126001d8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.9e8a3e2d31621c1bdf6139d068e7898a2ac2ab5a

[√] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at C:\DevTools\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.3
    • ANDROID_HOME = C:\DevTools\Android\sdk
    • Java binary at: C:\DevTools\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\DevTools\Android\AndroidStudio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.4127.31

[√] Connected devices
    • SM A300FU                 • c096d8a0      • android-arm • Android 6.0.1 (API 23)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

**Comment by kostaa** [comment]
Sorry accidentally closed the issue.

**Comment by brianegan** [comment]
Haha, dang it! 

Using the same version of Flutter, the example is working for me on the iOS / Android Emulator as well as on my Pixel phone. The only difference I spot is that you're on Windows and I'm on a Mac. 

I'll try this example out on my Windows device to see if that's the difference. Ideas:

  - Edit the `pubspec.yaml` in the `example` to reference the 5.0.0 package rather than using the `path: ../`? E.g. `font_awesome_flutter: 5.0.0`.
  - If that doesn't work, please download the attached Font Awesome zip. Unzip the Font Assets into the `assets` folder of this lib. In the `pubspec.yaml` of the library itself, try using the `ttf` instead of the `woff`.

Thanks for letting me know

**Comment by brianegan** [comment]
Hey @kostaa, could you please help me by trying one thing: I've actually been migrating this library to the latest version of Font Awesome (5.0.2). Could you please try the "font-awesome-5" branch to see if that works for ya?

**Comment by kostaa** [comment]
No problem will do tonight (London time)

**Comment by kostaa** [comment]
Hi Brian,

Sorry have not gone very far on this. 
Having gradle build issues not sure what causes it. 
Will let you know once I manage to sort it out.

Regards,
Adam

**Comment by brianegan** [comment]
Hey Adam, no worries at all! Thanks for your efforts.

**Comment by Gnorme** [comment]
I'm having the same issue as well. 

When I try to import using:

`import 'package:font_awesome_flutter/font_awesome_flutter.dart';`

I get an error in VSCode:

`[dart] Target of URI doesn't exist: 'package:font_awesome_flutter/font_awesome_flutter.dart'.`

I've tried with:
`font_awesome_flutter: ^5.0.0`
and downloading the package and using:
```
font_awesome_flutter:
    path: ../
```

Developing on Windows 7
Testing on Android

**Comment by brianegan** [comment]
Thanks for the report @Gnorme -- Hrm, that error seems like a bit of an odd one. Are you able to build the project at all with `flutter run`, or does that report the same "Can't find package" error?

As long as you've run `flutter packages get` in the root of the `example` directory (not the main library), the package should certainly exist. Have you have this trouble with any other packages?

**Comment by brianegan** [comment]
@Gnorme @kostaa Hey all, thanks again for reporting this! Turns out, the official CupertinoIcons from the Flutter also have this problem, meaning there's a problem at the Flutter level. I've filed a bug with the Flutter team:

https://github.com/flutter/flutter/issues/13870

In addition, I also saw the "Target of URI doesn't exist" error on Windows. To make it work, I had to open the `example` folder as it's own project rather than as part of the whole package. This works on Mac, so I think it's a problem with the Dart analyzer. Please consider filing a bug on the official github repo for the dart SDK to report this issue!

**Comment by Gnorme** [comment]
Hmm... I was able to get the error to go away in the example by opening it as it's own project but I'm trying to use it in my own project which is already separate and I'm still getting the error.

I've run `flutter packages get` and I can still build my project with `flutter run` after adding font_awesome_flutter to my dependencies and importing. I get the boxes with X where the icons should be though which is why I thought it might be related. I have not had this issue with any other packages.

**Comment by brianegan** [comment]
@Gnorme Yah, I think there are two separate problems reported here:

  1. The boxes issue, which I think is a real bug with Flutter (even the official Flutter packages suffer from this problem, Issue reported here: https://github.com/flutter/flutter/issues/13870)
  2. The `Target of URI doesn't exist` issue, which seems to relate to the dart analyzer. For some reason, the dart analyzer is unable to find a package that exists in the pubspec. You may want to file a follow-up bug with the dart sdk repo if you run into that problem more frequently, but is not something I can fix with this project.

**Comment by brianegan** [comment]
Hey all, the underlying issue with Flutter has been fixed, and it also fixed this issue! Gonna go ahead and close it out now that it works once again on Windows :)

![screenshot_1517618300](https://user-images.githubusercontent.com/126604/35760802-90ba6594-0837-11e8-9982-c8c77ebb5c5e.png)

**Comment by kostaa** [comment]
All is good - thank you!

**Comment by rahulreghupdm** [comment]
> Hey all, the underlying issue with Flutter master branch has been fixed, and it also fixed this issue! Gonna go ahead and close it out now that it works once again on Windows :)
> 
> ![screenshot_1517618300](https://user-images.githubusercontent.com/126604/35760802-90ba6594-0837-11e8-9982-c8c77ebb5c5e.png)

can you share the details that how fix this bug
